package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_agent", "agentId", Agent.class);
		arp.addMapping("t_order", "orderId", Order.class);
		arp.addMapping("t_feedback", "id", Feedback.class);
		arp.addMapping("t_photo", "photoId", Photo.class);
		arp.addMapping("t_postcard", "merchandiseId", Postcard.class);
		//管理员表
		arp.addMapping("t_administrator", "id", Administrator.class);
		arp.addMapping("t_scenic", "scenicId", Scenic.class);
		arp.addMapping("t_scenicboard", "sceninBoardId", Scenicboard.class);
		arp.addMapping("t_scenicmoenyrecord", "recordId", Scenicmoenyrecord.class);
		arp.addMapping("t_scenicpic", "scenicPicId", Scenicpic.class);
		//用户的应用表
		arp.addMapping("t_user", "id", Useradministrator.class);
		//登录用户表 是需要换掉的先放这里
		arp.addMapping("t_comment", "id", Comment.class);
		arp.addMapping("t_fakeuser", "id", Fakeuser.class);
		arp.addMapping("t__backstage_login", "id", Backstagelogin.class);
		//老板物语两张表的映射
		arp.addMapping("t_bossmsg", "id",Bossmsg.class);
		arp.addMapping("t_bossuser", "id",Bossuser.class);
		arp.addMapping("t_wxaqrcode", "id",wxaqrcode.class);
		arp.addMapping("t_template", "templateId",Template.class);
	
		arp.addMapping("t_scenicdrawmoneyrecord", "id", Scenicdrawmoneyrecord.class);
		arp.addMapping("t_info", "id", Info.class);
		
		arp.addMapping("t_guide", "id",Guide.class);
	}
}

