package com.demo.common.model;

import com.demo.common.model.base.BaseAgentmoenyrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Agentmoenyrecord extends BaseAgentmoenyrecord<Agentmoenyrecord> {
	public static final Agentmoenyrecord dao = new Agentmoenyrecord().dao();
}
