package com.demo.common.model;


import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Agentdrawmoneyrecord extends Model<Agentdrawmoneyrecord> {
	public static final Agentdrawmoneyrecord dao = new Agentdrawmoneyrecord().dao();
	
	//分页查询订单
		 public Page<Agentdrawmoneyrecord> paginate1(int pageNumber, int pageSize,String sqlstr) {
			 		return paginate(pageNumber, pageSize, "select *",sqlstr);
			}
	
}
