package com.demo.common.model;


import java.util.List;

import com.hwmao.util.CommonUtils;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Backstagelogin extends Model<Backstagelogin> {
	public static final Backstagelogin dao = new Backstagelogin().dao();
	
	//登陆时间的记录 如果这个用户存在就 去更新，不存在就去新建一个
	@SuppressWarnings("static-access")
	public void updatelogin(int userId) {
		List<Backstagelogin> backstagelogins=Backstagelogin.dao.find("select *from t__backstage_login where userId=?",userId);
		int ctime=new CommonUtils().getNowDateTime();
		int agentId=new Scenic().findById(userId).getInt("agentId");
		String nickname=new Agent().findById(agentId).getAgentname();
		if (backstagelogins.size()>0) {
			//存在这个用户就去创建
			Db.update("update t__backstage_login set ctime =? where userId=?",ctime,userId);
		}else {
			//不存在这个用户就去创建
			new Backstagelogin().set("userId", userId).set("ctime", ctime).set("nickname", nickname).set("types", 3).save();
		}
	}
}
