package com.demo.common.model;

import com.demo.common.model.base.BaseHwmaomoenyrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hwmaomoenyrecord extends BaseHwmaomoenyrecord<Hwmaomoenyrecord> {
	public static final Hwmaomoenyrecord dao = new Hwmaomoenyrecord().dao();
}
