package com.demo.common.model;


import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Info extends Model<Info> {
	public static final Info dao = new Info().dao();
}
