package com.demo.common.model;

import com.demo.common.model.base.BaseLogininfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Logininfo extends BaseLogininfo<Logininfo> {
	public static final Logininfo dao = new Logininfo().dao();
}
