package com.demo.common.model;

import com.demo.common.model.base.BaseMoenyrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Moenyrecord extends BaseMoenyrecord<Moenyrecord> {
	public static final Moenyrecord dao = new Moenyrecord().dao();
}
