package com.demo.common.model;

import com.demo.common.model.base.BaseOperatelog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operatelog extends BaseOperatelog<Operatelog> {
	public static final Operatelog dao = new Operatelog().dao();
}
