package com.demo.common.model;

import com.demo.common.model.base.BasePayrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Payrecord extends BasePayrecord<Payrecord> {
	public static final Payrecord dao = new Payrecord().dao();
}
