package com.demo.common.model;

import com.demo.common.model.base.BasePostcard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Postcard extends BasePostcard<Postcard> {
	public static final Postcard dao = new Postcard().dao();
}
