package com.demo.common.model;

import com.demo.common.model.base.BaseScenicmoenyrecord;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Scenicmoenyrecord extends BaseScenicmoenyrecord<Scenicmoenyrecord> {
	public static final Scenicmoenyrecord dao = new Scenicmoenyrecord().dao();
	
	
	 public Page<Scenicmoenyrecord> paginate(int pageNumber, int pageSize,String sqlstr) {
	 		return paginate(pageNumber, pageSize, "select *",sqlstr);
	}
}
