package com.demo.common.model;

import com.demo.common.model.base.BaseSupport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Support extends BaseSupport<Support> {
	public static final Support dao = new Support().dao();
}
