package com.demo.common.model;

import com.demo.common.model.base.BaseSystemuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Systemuser extends BaseSystemuser<Systemuser> {
	public static final Systemuser dao = new Systemuser().dao();
}
