package com.demo.common.model;

import com.demo.common.model.base.BaseTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Template extends BaseTemplate<Template> {
	public static final Template dao = new Template().dao();
}
