package com.demo.common.model;

import com.demo.common.model.base.BaseUserrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userrecord extends BaseUserrecord<Userrecord> {
	public static final Userrecord dao = new Userrecord().dao();
}
