package com.demo.common.model;

import com.demo.common.model.base.BaseUserLogin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLogin extends BaseUserLogin<UserLogin> {
	public static final UserLogin dao = new UserLogin().dao();
}
