package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserrecord<M extends BaseUserrecord<M>> extends Model<M> implements IBean {

	public M setOenpid(java.lang.Integer oenpid) {
		set("oenpid", oenpid);
		return (M)this;
	}

	public java.lang.Integer getOenpid() {
		return get("oenpid");
	}

	public M setAction(java.lang.Integer action) {
		set("action", action);
		return (M)this;
	}

	public java.lang.Integer getAction() {
		return get("action");
	}

	public M setScenicId(java.lang.Integer scenicId) {
		set("scenicId", scenicId);
		return (M)this;
	}

	public java.lang.Integer getScenicId() {
		return get("scenicId");
	}

	public M setScenicboardId(java.lang.Integer scenicboardId) {
		set("scenicboardId", scenicboardId);
		return (M)this;
	}

	public java.lang.Integer getScenicboardId() {
		return get("scenicboardId");
	}

	public M setCtime(java.util.Date ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.util.Date getCtime() {
		return get("ctime");
	}

	public M setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
		return (M)this;
	}

	public java.lang.String getLatitude() {
		return get("latitude");
	}

	public M setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
		return (M)this;
	}

	public java.lang.String getLongitude() {
		return get("longitude");
	}

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

}
