package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public M setMessageId(java.lang.Integer messageId) {
		set("messageId", messageId);
		return (M)this;
	}

	public java.lang.Integer getMessageId() {
		return get("messageId");
	}

	public M setUnion(java.lang.String union) {
		set("union", union);
		return (M)this;
	}

	public java.lang.String getUnion() {
		return get("union");
	}

	public M setCtime(java.lang.Integer ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.lang.Integer getCtime() {
		return get("ctime");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public M setLocation(java.lang.String location) {
		set("location", location);
		return (M)this;
	}

	public java.lang.String getLocation() {
		return get("location");
	}

	public M setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
		return (M)this;
	}

	public java.lang.String getIntroduce() {
		return get("introduce");
	}

	public M setSelection(java.lang.Integer selection) {
		set("selection", selection);
		return (M)this;
	}

	public java.lang.Integer getSelection() {
		return get("selection");
	}

}
