package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLogininfo<M extends BaseLogininfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setAcount(java.lang.String acount) {
		set("acount", acount);
		return (M)this;
	}

	public java.lang.String getAcount() {
		return get("acount");
	}

	public M setCtime(java.lang.Integer ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.lang.Integer getCtime() {
		return get("ctime");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

}
