package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setBirth(java.util.Date birth) {
		set("birth", birth);
		return (M)this;
	}

	public java.util.Date getBirth() {
		return get("birth");
	}

	public M setJoindate(java.util.Date joindate) {
		set("joindate", joindate);
		return (M)this;
	}

	public java.util.Date getJoindate() {
		return get("joindate");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setEpassword(java.lang.String epassword) {
		set("epassword", epassword);
		return (M)this;
	}

	public java.lang.String getEpassword() {
		return get("epassword");
	}

	public M setEmial(java.lang.String emial) {
		set("emial", emial);
		return (M)this;
	}

	public java.lang.String getEmial() {
		return get("emial");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return get("sex");
	}

}
