package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTest<M extends BaseTest<M>> extends Model<M> implements IBean {

	public M setID(java.lang.Integer ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public M setName(java.lang.String Name) {
		set("Name", Name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("Name");
	}

	public M setParentName(java.lang.String ParentName) {
		set("ParentName", ParentName);
		return (M)this;
	}

	public java.lang.String getParentName() {
		return get("ParentName");
	}

	public M setLevel(java.lang.String Level) {
		set("Level", Level);
		return (M)this;
	}

	public java.lang.String getLevel() {
		return get("Level");
	}

	public M setDesc(java.lang.String Desc) {
		set("Desc", Desc);
		return (M)this;
	}

	public java.lang.String getDesc() {
		return get("Desc");
	}

}
