package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseScenic<M extends BaseScenic<M>> extends Model<M> implements IBean {

	public M setScenicId(java.lang.Integer scenicId) {
		set("scenicId", scenicId);
		return (M)this;
	}

	public java.lang.Integer getScenicId() {
		return get("scenicId");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public M setTelphone1(java.lang.String telphone1) {
		set("telphone1", telphone1);
		return (M)this;
	}

	public java.lang.String getTelphone1() {
		return get("telphone1");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setCtime(java.lang.Integer ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.lang.Integer getCtime() {
		return get("ctime");
	}

	public M setAgentId(java.lang.Integer agentId) {
		set("agentId", agentId);
		return (M)this;
	}

	public java.lang.Integer getAgentId() {
		return get("agentId");
	}

	public M setMoney(java.lang.String money) {
		set("money", money);
		return (M)this;
	}

	public java.lang.String getMoney() {
		return get("money");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public M setScenicboardaccount(java.lang.Integer scenicboardaccount) {
		set("scenicboardaccount", scenicboardaccount);
		return (M)this;
	}

	public java.lang.Integer getScenicboardaccount() {
		return get("scenicboardaccount");
	}

	public M setScenicboardremain(java.lang.Integer scenicboardremain) {
		set("scenicboardremain", scenicboardremain);
		return (M)this;
	}

	public java.lang.Integer getScenicboardremain() {
		return get("scenicboardremain");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public M setCounty(java.lang.String county) {
		set("county", county);
		return (M)this;
	}

	public java.lang.String getCounty() {
		return get("county");
	}

	public M setDetailaddress(java.lang.String detailaddress) {
		set("detailaddress", detailaddress);
		return (M)this;
	}

	public java.lang.String getDetailaddress() {
		return get("detailaddress");
	}

	public M setTime(java.lang.String time) {
		set("time", time);
		return (M)this;
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public M setLoginname(java.lang.String loginname) {
		set("loginname", loginname);
		return (M)this;
	}

	public java.lang.String getLoginname() {
		return get("loginname");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setContactname(java.lang.String contactname) {
		set("contactname", contactname);
		return (M)this;
	}

	public java.lang.String getContactname() {
		return get("contactname");
	}

	public M setBankname(java.lang.String bankname) {
		set("bankname", bankname);
		return (M)this;
	}

	public java.lang.String getBankname() {
		return get("bankname");
	}

	public M setBankaccount(java.lang.String bankaccount) {
		set("bankaccount", bankaccount);
		return (M)this;
	}

	public java.lang.String getBankaccount() {
		return get("bankaccount");
	}

	public M setBankaddress(java.lang.String bankaddress) {
		set("bankaddress", bankaddress);
		return (M)this;
	}

	public java.lang.String getBankaddress() {
		return get("bankaddress");
	}

}
