package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTemplate<M extends BaseTemplate<M>> extends Model<M> implements IBean {

	public M setTemplateId(java.lang.Integer templateId) {
		set("templateId", templateId);
		return (M)this;
	}

	public java.lang.Integer getTemplateId() {
		return get("templateId");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setTypes(java.lang.Integer types) {
		set("types", types);
		return (M)this;
	}

	public java.lang.Integer getTypes() {
		return get("types");
	}

	public M setScennicId(java.lang.Integer scennicId) {
		set("scennicId", scennicId);
		return (M)this;
	}

	public java.lang.Integer getScennicId() {
		return get("scennicId");
	}

}
