package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMoenyrecord<M extends BaseMoenyrecord<M>> extends Model<M> implements IBean {

	public M setMoneyId(java.lang.Integer moneyId) {
		set("moneyId", moneyId);
		return (M)this;
	}

	public java.lang.Integer getMoneyId() {
		return get("moneyId");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("orderId", orderId);
		return (M)this;
	}

	public java.lang.Integer getOrderId() {
		return get("orderId");
	}

	public M setAmountT(java.lang.String amountT) {
		set("amountT", amountT);
		return (M)this;
	}

	public java.lang.String getAmountT() {
		return get("amountT");
	}

	public M setCtime(java.util.Date ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.util.Date getCtime() {
		return get("ctime");
	}

	public M setScenicId(java.lang.Integer scenicId) {
		set("scenicId", scenicId);
		return (M)this;
	}

	public java.lang.Integer getScenicId() {
		return get("scenicId");
	}

	public M setAgentId(java.lang.Integer agentId) {
		set("agentId", agentId);
		return (M)this;
	}

	public java.lang.Integer getAgentId() {
		return get("agentId");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public M setScenicT(java.lang.String scenicT) {
		set("scenicT", scenicT);
		return (M)this;
	}

	public java.lang.String getScenicT() {
		return get("scenicT");
	}

	public M setAgentT(java.lang.String agentT) {
		set("agentT", agentT);
		return (M)this;
	}

	public java.lang.String getAgentT() {
		return get("agentT");
	}

	public M setHwmaoT(java.lang.String hwmaoT) {
		set("hwmaoT", hwmaoT);
		return (M)this;
	}

	public java.lang.String getHwmaoT() {
		return get("hwmaoT");
	}

}
