package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserLogin<M extends BaseUserLogin<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setSessionKey(java.lang.String sessionKey) {
		set("session_key", sessionKey);
		return (M)this;
	}

	public java.lang.String getSessionKey() {
		return get("session_key");
	}

	public M setTrdsessionKey(java.lang.String trdsessionKey) {
		set("trdsession_key", trdsessionKey);
		return (M)this;
	}

	public java.lang.String getTrdsessionKey() {
		return get("trdsession_key");
	}

	public M setCtime(java.lang.Integer ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.lang.Integer getCtime() {
		return get("ctime");
	}

	public M setUnion(java.lang.String union) {
		set("union", union);
		return (M)this;
	}

	public java.lang.String getUnion() {
		return get("union");
	}

}
