package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSupport<M extends BaseSupport<M>> extends Model<M> implements IBean {

	public M setSupportId(java.lang.Integer supportId) {
		set("supportId", supportId);
		return (M)this;
	}

	public java.lang.Integer getSupportId() {
		return get("supportId");
	}

	public M setCtime(java.lang.Integer ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.lang.Integer getCtime() {
		return get("ctime");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public M setPhotoId(java.lang.Integer photoId) {
		set("photoId", photoId);
		return (M)this;
	}

	public java.lang.Integer getPhotoId() {
		return get("photoId");
	}

	public M setUnion(java.lang.String union) {
		set("union", union);
		return (M)this;
	}

	public java.lang.String getUnion() {
		return get("union");
	}

	public M setTypes(java.lang.Integer types) {
		set("types", types);
		return (M)this;
	}

	public java.lang.Integer getTypes() {
		return get("types");
	}

}
