package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseScenicboard<M extends BaseScenicboard<M>> extends Model<M> implements IBean {

	public M setSceninBoardId(java.lang.Integer sceninBoardId) {
		set("sceninBoardId", sceninBoardId);
		return (M)this;
	}

	public java.lang.Integer getSceninBoardId() {
		return get("sceninBoardId");
	}

	public M setTittle(java.lang.String tittle) {
		set("tittle", tittle);
		return (M)this;
	}

	public java.lang.String getTittle() {
		return get("tittle");
	}

	public M setScenicId(java.lang.Integer scenicId) {
		set("scenicId", scenicId);
		return (M)this;
	}

	public java.lang.Integer getScenicId() {
		return get("scenicId");
	}

	public M setLatitude(java.lang.Double latitude) {
		set("latitude", latitude);
		return (M)this;
	}

	public java.lang.Double getLatitude() {
		return get("latitude");
	}

	public M setLongitude(java.lang.Double longitude) {
		set("longitude", longitude);
		return (M)this;
	}

	public java.lang.Double getLongitude() {
		return get("longitude");
	}

	public M setCtime(java.lang.Integer ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.lang.Integer getCtime() {
		return get("ctime");
	}

	public M setPv(java.lang.Integer pv) {
		set("pv", pv);
		return (M)this;
	}

	public java.lang.Integer getPv() {
		return get("pv");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public M setEffectiveRange(java.lang.Integer effectiveRange) {
		set("effectiveRange", effectiveRange);
		return (M)this;
	}

	public java.lang.Integer getEffectiveRange() {
		return get("effectiveRange");
	}

	public M setDis(java.lang.Double dis) {
		set("dis", dis);
		return (M)this;
	}

	public java.lang.Double getDis() {
		return get("dis");
	}

}
