package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePostcard<M extends BasePostcard<M>> extends Model<M> implements IBean {

	public M setMerchandiseId(java.lang.Integer merchandiseId) {
		set("merchandiseId", merchandiseId);
		return (M)this;
	}

	public java.lang.Integer getMerchandiseId() {
		return get("merchandiseId");
	}

	public M setOpenId(java.lang.String openId) {
		set("openId", openId);
		return (M)this;
	}

	public java.lang.String getOpenId() {
		return get("openId");
	}

	public M setTo(java.lang.String to) {
		set("to", to);
		return (M)this;
	}

	public java.lang.String getTo() {
		return get("to");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public M setPhotoUrl(java.lang.String photoUrl) {
		set("photoUrl", photoUrl);
		return (M)this;
	}

	public java.lang.String getPhotoUrl() {
		return get("photoUrl");
	}

	public M setCtime(java.lang.String ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.lang.String getCtime() {
		return get("ctime");
	}

	public M setTypes(java.lang.Integer types) {
		set("types", types);
		return (M)this;
	}

	public java.lang.Integer getTypes() {
		return get("types");
	}

}
